# -*- coding: utf-8 -*-

# Smaller list of cities for testing purposes
SOME_CITY_NAMES = {
	'CITIES': [
		'Calgary',
		'Berlin',
		'Tokyo',
		'London'
	]
}

# List of all cities to calculate the sunset for
ALL_CITY_NAMES = {
	'AFRICA': [
		'Accra',
		'Dakar',
		'Pretoria',
		'Tripoli',
		'Abuja',
		'Kampala',
		'Bamako',
		'Rabat',
		'Antananarivo',
		'Ouagadougou',
		'Conakry',
		'Tunis',
		'Freetown',
		'Monrovia',
	#Central Africa
		#Burkina Faso
		'Ouagadougou',
		'Ouahigouya',
		'Kaya',
		'Bobo Dioulasso',
		'Banfora',
		'Koudougou',
		#Chad
		'N\'Djamena',
		'Moundou',
		'Sarh',
		'Abeche',
		'Kelo',
		'Fada',
		'Um Dukhun',
		#Democratic republic of the Congo
		'Kinshasa',
		'Gemena',
		'Isiro',
		'Bumba',
		'Bandundu',
		'Kamina',
		'Lubumbashi',
		'Mbuji-Mayi',
		'Kananga',
		'Kisangani',
		'Tshikapa',
		'Kolwezi',
		'Likasi',
		'Kikwit',
		#Republic of the Congo
		'Brazzaville',
		'Pointe-Noire',
		'Dolisie',
		'Loubomo',
		'Nkayi',
		'Malabo',
		'Libreville',
		'Zanaga',
	#East Africa
		#Burundi
		'Bujumbura',
		'Gitega',
		'Magamba',
		'Mutumba',
		'Ngozi',
		'Ruyigi',
		#Cameroon
		'Douala',
		'Yaounde',
		'Bamenda',
		'Bafoussam',
		'Bertoua',
		'Malabo',
		'Garoua',
		'Kumbo',
		'Maroua',
		'Mokolo',
		'Ngaoundere',
		'Kumba',
		'Buea',
		'Nkongsamba',
		#Djibouti
		'Djibouti City',
		'Obock',
		'Fagal',
		'Dorra',
		'Yoboki',
		'Ali Sabieh',
		#Equatoril Guinea
		'Djibloho',
		'Jaaye',
		'Malabo',
		#Ethiopia
		'Addis Ababa',
		'Adwa',
		'Bahir Dar',
		'Mek\'ele',
		'Dire Dawa',
		'Dessie',
		'Adama',
		'Awassa',
		'Finchawa',
		'Gondar',		
		'Hahaya',		
		'Mombasa',
		'Nairobi',
		'Kigali',
		'Entebbe',
	#Horn of Africa
		'Djibouti City',
		'Bosaso',
		'Berbera',
		'Asmara',
		'Hobyo',
		'Hargeisa',
		'Socotra',
		'Mogadishu',
		#Bennin
		'Banikoara',
		'Cotonou',
		'Porto Novo',
		'Parakou',
		'Djougou',
		'Bohicon',
		'Kandi',
		'Abomey',
		'Natitingou',
		'Lokossa',
		'Ouidah',
		'Parahou',
		#Eritrea
		'Agra',
		'Asmara',
		'Anker',
		'Baden',
		'Dara',
		'Hasta',
		'Kanora',
		'Keren',
		'Maho',
		'Mendefera',
		'Teseney',
		#Egypt
		'Cairo',
		'Alexandria',
		'Mansoura',
		'Port Said',
		'Suez',
		'Aswan',

	#North Africa
		#Algeria
		'Algiers',
		'Oran',
		'Constantine',
		'Annaba',
		'Blida',
		'Batna',
		'Bordj Badji Mokhtar',
		'Djelfa',
		'Djanet',
		'Illizi',
		'Ouargla',
		'Setif',
		'Sfax',
		'Sousse',
		'Sidi Bel Abbes',
		'Reggane',
		'Biskra',
		'Tebessa',
		'Aoulef',
		'Adrar',
		'Tunis',
		'Tinduf',
		'Benghazi',
		'Sebha',
		'Casablanca',
		'Marrakech',
		'Khartoum',
		'Djerba',
		'Monastir',
		'Carthage',
		'Dakhla',
		'Misrata',
		'Rabat',
		'Fes',
		'Nouakchott',
		'Agadez',
	#Southern Africa
		#Angoloa
		'Luanda',
		'Benguela',
		'Belas',
		'Cabinda',
		'Cuvelai',
		'Ganda',
		'Huambo',
		'Lubango',
		'Kuito',
		'Malanje',
		'Menongue',
		'Namacunde',
		'Namibe',
		'Soyo',
		'Lobito',
		'Benguela',
		'Uige',
		#Botswana
		'Antisiranana',
		'Gaborone',
		'Francistown',
		'Molepolole',
		'Lubango',
		'Kanye',
		'Maun',
		'Maseru',
		'Mahajanga',
		'Sehithwa',
		'Toamasina',
		'Toliara',
		'Maputo',
		'Windhoek',
		'Cape Town',
		'Johannesburg',
		'Manzini',
		'Lusaka',
		'Harare',
		'Xakanaxa',
	],
	'AMERICAS': [
		'Buenos Aires',
		'Lima',
		'Santiago',
		'Brasilia',
		'Seattle',
		'Santo Domingo',
		'Caracas',
		'San Juan',
	# Canada
		'Baker Lake',
		'Banff',
		'Beaver Creek',
		'Iquluit',
		'Cape Dorset',
		'Cambridge Bay',
		'Dawson Creek',
		'Destruction Bay',
		'Deer Lake',
		'Fort McMurray',
		'Fort Mackenzie',
		'Fort McPherson',
		'Saguenay',
		'Calgary',
		'Charlottetown',
		'Churchill',
		'Edmonton',
		'Fredericton',
		'Gjoa Haven',
		'Halifax',
		'Hamilton',
		'Iqaluit',
		'Ivujivik',
		'Kelowna',
		'Kimmirut',
		'Labrador City',
		'Moncton',
		'Montreal',
		'Mosquito Lake',
		'Norman Wells',
		'Ottawa',
		'Paulatuk',
		'Prince George',
		'Prince Rupert',
		'Quebec City',
		'Regina',
		'Repulse Bay',
		'Saguenay',
		'Saskatoon',
		'Sidbury',
		'St. John\'s',
		'Toronto',
		'Thunder Bay',
		'Tuktoyaktuk',
		'Vancouver',
		'Victoria',
		'Umingmaktok',
		'Whitehorse',
		'Winnipeg',
		'Wrigley',
		'Yellowknife',
	# United States
		'Albany',
		'Albuquerque',
		'Anchorage',
		'Artic Village',
		'Atlanta',
		'Austin',
		'Baltimore',
		'Bismarck',
		'Boston',
		'Buffalo',
		'Chicago',
		'Chattanooga',
		'Cincinnati',
		'Cleveland',
		'Corpus Christi',
		'Columbus',
		'Dallas',
		'Denver',
		'Detroit',
		'Deluth',
		'El Paso',
		'Fargo',
		'Fairbanks',
		'Great Falls',
		'Grand Junction',
		'Honolulu',
		'Hilo',
		'Houston',
		'Hooper Bay',
		'Indianapolis',
		'Jacksonville',
		'Key West',
		'King Cove',
		'Kailua-Kona',
		'Kansas City',
		'Las Vegas',
		'Los Angeles',
		'Louisville',
		'Lahania',
		'Memphis',
		'Miami',
		'Milwaukee',
		'Minneapolis',
		'Montgomery',
		'Myrtle Beach',
		'Nashville',
		'New Orleans',
		'New York',
		'New Jersey',
		'Oakland',
		'Odessa',
		'Palm Springs',
		'Philadelphia',
		'Phoenix',
		'Pittsburgh',
		'Point Hope',
		'Portland',
		'Prudhoe Bay',
		'Raleigh',
		'Rapid City',
		'Reno',
		'Rochester',
		'Sacramento',
		'Salt Lake City',
		'San Antonio',
		'San Diego',
		'San Francisco',
		'San Jose',
		'Seattle',
		'Sioux Falls',
		'Spokane',
		'Springfield',
		'Syracuse',
		'Tampa',
		'Tok',
		'Toledo',
		'Tucson',
		'Tulsa',
		'Wainwright',
		'Washington DC',
		'Wichita',
		'Yuma',
		'Yakutat',
	#Mexico
		'Acapulco',
		'Cabo San Lucas',
		'Chetumal',
		'Chihuahua',
		'Delicias',
		'Durango',
		'Guadalajara',
		'Hermosillo',
		'La Mochis',
		'Merida',
		'Mexico City',
		'Monterrey',
		'Puebla',
		'Tampico',
		'Tijuana',
		'Villahermosa',
		'Xalapa',
	#Caribbean
		'Aguadilla',
		'Belize City',
		'Belmopan',
		'Bocas del Toro Province',
		'Catacamas',
		'Cayman Islands',
		'Colon',
		'Nassau',
		'Georgetown',
		'Havana',
		'Juticalpa',
		'Jacmel',
		'Leon',
		'Liberia',
		'Limon',
		'Flores',
		'Gonaives',
		'Guatemala City',
		'Panama City',
		'Puerto Plata',
		'Puerto Cabezas',
		'Punta Cana',
		'Quetzaltenago',
		'Santo Domingo',
		'Santa Ana',
		'Santa Clara',
		'San Juan',
		'Santiago de los Caballeros',
		'San Jose de Costa Rica',
		'San Miguel',
		'San Pedro Sula',
		'San Salvador',
		'Grenada',
		'Granada',
		'Port-au-Prince',
		'Kingston',
		'Matanzas',
		'Montego Bay',
		'Managua',
		'Nassau',
		'Nueva Guinea',
		'Tela',
		'Tobago',
		'Tegucigalpa',
		'Veradero',
		'British Virgin Islands',
		'US Virgin Islands',
		'Barbados',
		'Saint Vincent and the Grenadines',
		'Saint Lucia',
		'Monserrat',
		'Aruba',
	#Central America
	#South America
		'Antofagasta',
		'Buenos Aires',
		'Mendoza',
		'Brasilia',
		'Curitiba',
		'Rio de Janeiro',
		'Santiago',
		'Cali',
		'Quito',
		'Cusco',
		'Lima',
		'Montevideo',
		'Caracas',
		'Maracaibo',
		'Trinidad and Tobago',
		'Manaus',
		'Guayaquil',
		'Rosario',
		'Asuncion',
		'Santa Cruz de la Sierra',
		'Paramaribo',
		'Georgetown',
		'New Island',
		'Port Stephens',
		'Puerto Montt',
		'Comodoro',
		'Mar del Plata',
		'Pelotas',
		'Cochabamba',
		'Natal',
		'Chimbote',
		'Barquisimeto',
		'Agua Buena',
		'Kralendijk',
		'Castries City',
		'Roseau',
		'Bridgetown',
		'Brades',
		'Beausejour',
		'Basse Terre',
		'Charlotte Amalie',
		'Vieques',
		'Cockburn Town',
		'Guantanamo',
		'Les Cayes',
		'Camaguey',
		'Moron',
		'Varadero',

	],
	'ASIA': [
	#Central Asia
		'Aktobe',
		'Andijan',
		'Almaty',
		'Astana',
		'Atyrau',
		'Uralsk',
		'Balkhash',
		'Bishkek',
		'Bukhara',
		'Chust',
		'Dushanbe',
		'Ferah',
		'Gujranwala',
		'Herat',
		'Isfara',
		'Istaravshan',
		'Jilikul',
		'Jizzakh',
		'Kandyagash',
		'Karaganda',
		'Khuzdar',
		'Karagandy',
		'Kashgar',
		'Kashi',
		'Kulob',
		'Kokshetau',
		'Kostanay',
		'Kunduz',
		'Kyzylorda',
		'Mary',
		'Mazar-i-Sharif',
		'Makat',
		'Merv',
		'Muborak',
		'Mianwali',
		'Nukus',
		'Ormara',
		'Qarshi',
		'Rahim',
		'Samarkand',
		'Sheberghan',
		'Shymkent',
		'Taraz',
		'Turkmenabat',
		'Turbat',
		'Urumqi',
		'Vose',
		'Yovon',
		'Khujand',
		'Ashgabat',
		'Namangan',
		'Tashkent',
		'Zabol',
	#East Asia
		#NorthKorea
		'Pyongyang',
		'Hamhung',
		'Chongjin',
		'Nampo',
		'Wonsan',
		'Sinuiju',
		'Tanchon',
		'Kaechon',
		'Kaesong',
		'Sariwon',
		#Japan
		'Yokohama',
		'Kobe',
		'Kyoto',
		'Fukuoka',
		'Kawasaki',
		'Saitama',
		'Sendai',
		'Kitakyushu',
		'Chiba',
		'Sakai',
		'Niigata',
		'Hamamatsu',
		'Kumamoto',
		'Sagamihara',
		'Shizuoka',
		'Hiroshima',
		'Nagasaki',
		'Osaka',
		'Sapporo',
		'Tokyo',
		'Nagoya',
		'Macau',
		'Fukushima',
		'Matsue',
		'Oita',
		'Fukuyama',
		'Kanazawa',
		'Nagano',
		'Otaru',
		'Hakodate',
		'Kushiro',
		'Tomakomai',
		'Aomori',
		'Hachinohe',
		#Mongolia
		'Ulan Bator',
		'Erdenet',
		'Darkhan',
		'Choibalsan',
		'Moron',
		'Matad',
		'Ulaanbaatar',
		'Murun',
		'Ulaangom',
		'Ulgii',
		'Sainshand',
		'Bogd',
		'Songino',
		'Chinggis',
		#China
		'Beijing',
		'Shanghai',
		'Guangzhou',
		'Shenzhen',
		'Chongqing',
		'Hong Kong',
		'Hangzhou',
		'Wuhan',
		'Harbin',
		'Kunming',
		'Dongguan',
		'Chengdu',
		'Nanjing',
		'Shenyang',
		'Suzhou',
		'Jinan',
		'Xi\'an',
		'Wuxi',
		'Hefei',
		'Changchun',
		'Changzhou',
		'Dalian',
		'Taiyuan',
		'Zhengzhou',
		'Changsha',
		'Ningbo',
		'Qingdao',
		'Zibo',
		'Fuzhou',
		'Nanning',
		'Altay',
		'Nanyang',
		'Rikaze',
		'Lhasa',
		'Yushu',
		'Golog',
		'Wuhai',
		'Hami',
		'Turpan',	
		#SouthKorea
		'Busan',
		'Seoul',
		'Incheon',
		'Daegu',
		'Daejeon',
		'Gwangju',
		'Ulsan',
		'Suwon',
		'Changwon',
		'Seongnam',
		'Goyang',
		'Yongin',
		'Bucheon',
		'Ansan',
		'Cheongju',
		'Jeonju',
		'Anyang',
		'Cheonan',
		'Namyangju',
		'Pohang',
		#Taiwan
		'Taipei',
		'Kaohsiung',
		'Taichung',
		'Tainan',
		'Hsinchu',
		'Taoyuan',
		'Keelung',
		'Zhongli',
		'Chiayi',
		'Changhua',
		'Pingtung',
		'Pingzhen',
		'Bade',
		'Yangmei',
		'Tianjin',
		'Shenyang',

	#South Asia
		'Chittagong',
		'Dhaka',
		'Sylhet',
		'Bangalore',
		'Delhi',
		'Mumbai',
		'Kathmandu',
		'Islamabad',
		'Karachi',
		'Colombo',
		'Coimbatore',
		'Galle',
		'Hambantota',
		'Ahmedabad',
		'Kolkata',
		'Chennai',
		'Hyderabad',
		'Ahmedabad',
		'Pune',
		'New Delhi',
		'Karachi',
		'Multan',
		'Lahore',
		'Faisalabad',
		'Kanpur',
		'Madurai',
		'Vadodara',
		'Patna',
		'Rajkot',
		'Visakhapatnam',
		'Jessore',
		'Darjeeling',
		'Guwahati',
	#South East Asia
		'Phnom Penh',
		'Ho Chi Minh City',
		'Buon Ma Thuot',
		'Phnom Penh',
		'Poi Pet',
		'Krong Siem Reap',
		'Krong Battambang',
		'Pattaya',
		'Mersing',
		'Batam',
		'Pekan',
		'Myeik',
		'Dawei',
		'Mawlamyine',
		'Naypitaw',
		'Shwebo',
		'Bago',
		'Pathein',
		'Myitkyina',
		'Medan',
		'Banda Aceh',
		'Palembang',
		'Jakarta',
		'Bandung',
		'Semarang',
		'Surabaya',
		'Timor-Leste',
		'Teluk Ambon',
		'Manado',
		'Manokwari',
		'Popondetta',
		'Baguio',
		'Davao',
		'Tacloban',
		'Puerto Princesa',
		'Cotabato',
		'Butuan',
		'Sanya',
		'Mayabunder',
		'Makassar',
		'Palembang',
		'Jakarta',
		'Balikpapan',
		'Kendari',
		'Kuala Lumpur',
		'Penang',
		'Mandalay',
		'Langkawi',
		'Manila',
		'Kalibo',
		'Singapore',
		'Bangkok',
		'Chiang Mai',
		'Phuket',
		'Ko Samui',
		'Hai Phong',
	#South West Asia
		'Kabul',
		'Kandahar',
		'Shiraz',
		'Birjand',
		'Tehran',
		'Isfahan',
		'Baghdad',
		'Basra',
		'Tel Aviv',
		'Aqaba',
		'Kuwait City',
		'Beirut',
		'Muscat',
		'Doha',
		'Mecca',
		'Dammam',
		'Medina',
		'Jeddah',
		'Riyadh',
		'Damascus',
		'Latakia',
		'Abu Dhabi',
		'Dubai',
		'Farah',
		'Quetta',
		'Tabriz',
		'Basrah',
		'Mashhad',
		'Erbil',
		'Mosul',
		'Tabuk',
		'Jerusalem',
		'Haifa',
		'Taif',
		'Port Sudan',
		'Sana\'a',
		'Al Ain',
	],
	'EUROPE': [
		'Tirana',
		'Yerevan',
		'Gyumri',
		'Baku',
		'Ganja',
		'Nakhchivan',
		'Graz',
		'Klagenfurt',
		'Innsbruck',
		'Linz',
		'Salzburg',
		'Vienna',
		'Gomel',
		'Minsk',
		'Antwerp',
		'Brussels',
		'Banja Luka',
		'Sarajevo',
		'Tuzla',
		'Mostar',
		'Burgas',
		'Plovdiv',
		'Sofia',
		'Varna',
		#Croatia
		'Bjelovar',
		'Crikvenica',
		'Daruvar',
		'Dubrovnik',
		'Karlovac',
		'Kutina',
		'Koprivnica',
		'Makarska',
		'Osijek',
		'Pula',
		'Pozega',
		'Porec',
		'Rovinj',
		'Rijeka',
		'Sibenik',
		'Slavonski',
		'Split',
		'Vinkovci',
		'Vukovar',
		'Virovitica',
		'Varazdin',
		'Zadar',
		'Zagreb',
		#Cyprus
		'Bafra',
		'Dipkarpaz',
		'Girne',
		'Larnaca',
		'Nicosia',
		'Paphos',
		'Ercan',
		#Czech
		'Brno',
		'Bielsko Biala',
		'Chomutov',
		'Ceske Budejovice',
		'Jihlava',
		'Karlovy Vary',
		'Liberec',
		'Mlada Boleslav',
		'Most',
		'Nymburk',
		'Olomouc',
		'Ostrava',
		'Opava',
		'Plzen',
		'Prague',
		'Pardubice',
		#Denmark
		'Aabenraa',
		'Aalborg',
		'Aarhus',
		'Ebeltoft',
		'Frederikshavn',
		'Odense',
		'Frederiksberg',
		'Esbjerg',
		'Gentofte',
		'Gladsaxe',
		'Grenaa',
		'Holstebro',
		'Randers',
		'Kolding',
		'Billund',
		'Copenhagen',
		'Roskilde',
		'Skagen',
		'Struer',
		'Thisted',
		'Viborg',
		#Estonia
		'Elva',
		'Keila',
		'Kardla',
		'Kuressaare',
		'Kohtla-Jarve',
		'Maardu',
		'Narva',
		'Tallinn',
		'Tartu',
		'Rapla',
		'Viljandi',
		#Finland
		'Helsinki',
		'Espoo',
		'Tampere',
		'Vantaa',
		'Oulu',
		'Lahti',
		'Kouvola',
		'Pori',
		'Joensuu',
		'Kemi',
		'Sirkka',
		'Ivalo',
		'Nellim',
		'Inari',
		'Kuopio',
		'Kuusamo',
		'Lappeenranta',
		'Oulu',
		'Rovaniemi',
		'Tampere Pirkkala',
		'Turku',
		'Vaasa',
		#France
		'Ajaccio',
		'Angers',
		'Bastia',
		'Beauvais',
		'Bergerac',
		'Biarritz',
		'Bordeaux',
		'Bourges',
		'Brest',
		'Caen',
		'Cannes',
		'Clermont-Ferrand',
		'Carcassonne',
		'Champagne sur Oise',
		'Dijon',
		'Dinard',
		'Figari Sud Corse',
		'Grenoble Isrre',
		'La Rochelle',
		'Le Havre',
		'Lille Lesquin',
		'Limoges',
		'Lyon',
		'Marseille',
		'Montpellier',
		'Mulhouse',
		'Nantes',
		'Nice',
		'Nimes',
		'Pau',
		'Paris',
		'Perpignan',
		'Poitiers',
		'Reims',
		'Rennes',
		'Rodez',
		'Strasbourg',
		'Toulon',
		'Toulouse',
		'Tours',
		#Georgia
		'Akhaltsikhe',
		'Batumi',
		'Borjomi',
		'Tsageri',
		'Oni',
		'Telavi',
		'Kvareli',
		'Kaspi',
		'Tbilisi',
		'Kutaisi',
		'Rustavi',
		'Zugdidi',
		'Gori',
		'Poti',
		'Samtredia',
		'Khashuri',
		'Senaki',
		#Germany
		'Augsburg',
		'Baden',
		'Berlin',
		'Bonn',
		'Bielefeld',
		'Brayreuth',
		'Bremen',
		'Celle',
		'Cottbus',
		'Chemnitz',
		'Cologne',
		'Dortmund',
		'Dresden',
		'Essen',
		'Frankfurt',
		'Flensburg',
		'Fulda',
		'Friedrichshafen',
		'Greifswald',
		'Hamburg',
		'Hagen',
		'Hamm',
		'Heidelberg',
		'Hanover',
		'Ingolstadt',
		'Kassel',
		'Kiel',
		'Karlsruhe',
		'Leipzig',
		'Memmingen',
		'Mainz',
		'Mannheim',
		'Munich',
		'Norderstedt',
		'Nuremberg',
		'Rosenheim',
		'Stuttgart',
		'Schwerin',
		'Ulm',
		'Weeze',
		'Wolfsburg',
		'Wiesbaden',
		'Zzwickau',
		#Greece
		'Athens',
		'Arta',
		'Agrinio',
		'Alexandroupoli',
		'Aigio',
		'Arachova',
		'Corinth',
		'Chania',
		'Chios Island',
		'Corfu',
		'Drama',
		'Edessa',
		'Florina',
		'Grevena',
		'Heraklion',
		'Ioannina',
		'Kalamaria',
		'Komotini',
		'Kalabaka',
		'Karditsa',
		'Kalamata',
		'Karpathos Island',
		'Kavala',
		'Kefalonia Island',
		'Kos Island',
		'Lamia',
		'Larissa',
		'Lavadia',
		'Messolonghi',
		'Mykonos Island',
		'Mytilene',
		'Preveza',
		'Rhodes',
		'Samos',
		'Serres',
		'Sparti',
		'Santorini',
		'Skiathos Island',
		'Skyros Island',
		'Macedonia',
		'Thessaloniki',
		'Xanthi',
		'Patras',
		'Volos',
		'Zakynthos',
		#Greenland
		'Cape York',
		'Daneborg',
		'Etah',
		'Kangerlussuag',
		'Isortoq',
		'Ittoqqortoormiit',
		'Nord',
		'Nuuk',
		'Savissivik',
		'Siorapaluk',
		#Hungary
		'Baja',
		'Budapest',
		'Eger',
		'Esztergom',
		'Debrecen',
		'Gyor',
		'Keszthely',
		'Miskolc',
		'Szeged',
		'Szombathely',
		'Sopron',
		'Szolnok',
		#Iceland
		'Akureyri',
		'Dalvik',
		'Hellnar',
		'Reykjavik',
		'Kopavogur',
		'Akureyri',
		'Akranes',
		'Selfoss',
		#Ireland
		'Bray',
		'Cork',
		'Dublin',
		'Dingle',
		'Dundalk',
		'Kerry',
		'Kildare',
		'Knock',
		'Shannon',
		'Isle of Man',
		'Limerick',
		'Galway',
		'Waterford',
		'Drogheda',
		'Kilkenny',
		'Wexford',
		#Italy
		'Alghero',
		'Ancona',
		'Bari',
		'Palese',
		'Bergamo',
		'Bologna',
		'Brescia',
		'Brindisi',
		'Cagliari',
		'Elmas',
		'Catania',
		'Cuneo Levaldigi',
		'Florence',
		'Genoa',
		'Lamezia Terme',
		'Lecce',
		'Milan',
		'Naples',
		'Olbia',
		'Palermo',
		'Parma',
		'Perugia',
		'Pescara',
		'Pisa',
		'Rimini',
		'Rome',
		'Savona',
		'Trapani',
		'Trento',
		'Trieste',
		'Turin',
		'Udine',
		'Venice',
		'Verona',
		#Kosovo
		'Pristina',
		'Prizren',
		'Gjakove',
		#Latvia
		'Riga',
		'Liepaja',
		'Madona',
		'Talsi',
		'Jurmala',
		'Ventspils',
		'Daugavpils',
		#lithuania
		'Kaunas',
		'Plunge',
		'Alytys',
		'Rokiskis',
		'Klaipeda',
		'Palanga',
		'Siauliai',
		'Vilnius',
		#Luxembourg
		'Larochette',
		'Clervaux',
		'Wiltz',
		'Vianden',
		'Echternach',
		'Luxembourg',
		#Macedonia
		'Bitola',
		'Ohrid',
		'Tetovo',
		'Shtip',
		'Prilep',
		'Ohrid',
		'Bitola',
		'Gostivar',
		'Kochani',
		'Skopje',
		#Malta
		'Birkirkara',
		'Luqa',
		'Kemmuna',
		'Marsaxlokk',
		'Mdina',
		'Mosta',
		'Qormi',
		'Sliema',
		'Mellieha',
		'Valletta',
		#Moldova
		'Balti',
		'Briceni',
		'Camenca',
		'Orhei',
		'Ribnita',
		'Riscani',
		'Tiraspol',
		'Ungheni',
		'Bender',
		'Chisinau',
		#Montenegro
		'Berane',
		'Bijelo Polje',
		'Herceg Novi',
		'Niksic',
		'Pljevlja',
		'Podgorica',
		'Tivat',
		#Netherlands
		'Amsterdam',
		'Arnhem',
		'Amersfoort',
		'Breda',
		'Emmen',
		'Eindhoven',
		'Leeuwarden',
		'Groningen',
		'Dordrecht',
		'The Hague',
		'Rotterdam',
		'Zwolle',
		#Norway
		'Alta',
		'Alesund',
		'Andenes',
		'Bergen',
		'Drammen',
		'Hammerfest',
		'Haugesund',
		'Lakselv',
		'Oslo',
		'Stavanger',
		'Vardo',
		'Trondheim',
		'Kristiansand',
		'Fredrikstad',
		'Skien',
		#Poland
		'Bialystok',
		'Bydgoszcz',
		'Czestochowa',
		'Katowice',
		'Krakow',
		'Warsaw',
		'Wroclaw',
		'Lodz',
		'Poznan',
		'Gdansk',
		'Gdynia',
		'Szczecin',
		'Bydgoszcz',
		'Lublin',
		#Portugal
		'Braga',
		'Funchal',
		'Castelo Branco',
		'Chaves',
		'Coimbra',
		'Porto Santo',
		'Lisbon',
		'Leiria',
		'Porto',
		'Ponta Delgada',
		'Terceira',
		'Viana do Castelo',
		'Viseu',
		#Romania
		'Bucharest',
		'Cluj-Napoca',
		'Constanta',
		'Deva',
		'Drobeta-Turnu Severin',
		'Galati',
		'Iasi',
		'Oradea',
		'Satu Mare',
		'Sibiu',
		'Timisoara',
		'Tulcea',
		#Russia
		'Arkhangelsk',
		'Beringovsky',
		'Bilibino',
		'Chita',
		'Chelyabinsk',
		'Dikson',
		'Egvenkinot',
		'Irkutsk',
		'Izhevsk',
		'Kazan',
		'Khabarovsk Krai',
		'Kaliningrad',
		'Kheta',
		'Krasnodar',
		'Lavrentiya',
		'Markovo',
		'Moscow',
		'Murmansk',
		'Magadan',
		'Namtsy',
		'Nizhneyansk',        
		'Nizhniy Novgorod',
		'Norilsk',
		'Novosibirsk',
		'Orenburg',
		'Ossora',
		'Perm',
		'Pevek',
		'Provideniya',
		'Rostov on Don',
		'Saint Petersburg',
		'Salekhard',
		'Samara',
		'Savoonga',
		'Slautnoye',
		'Sochi',
		'Susuman',
		'Tyumen',
		'Tiksi',
		'Ufa',
		'Ulan-Ude',
		'Ust-Nera',
		'Ust-Kamchatsk',
		'Vladivostok',
		'Yakutsk',
		'Yekaterinburg',
		#Serbia
		'Belgrade',
		'Cacak',
		'Krusevac',
		'Leskovac',
		'Nis',
		'Novi Sad',
		'Novi Pazar',
		'Pancevo',
		'Sombor',
		'Zrenjanin',
		#Slovakia
		'Bratislava',
		'Kosice',
		'Levice',
		'Martin',
		'Nitra',
		'Poprad',
		'Presov',
		'Uzhhorod',
		'Trnava',
		'Zilina',
		#Slovenia
		'Celije',
		'Crnomelj',
		'Koper',
		'Kocevje',
		'Lendava',
		'Ljubljana',
		'Maribor',
		'Ptuj',
		#Spain
		'Alicante',
		'Albacete',
		'Asturias',
		'Badajoz',
		'Barcelona',
		'Bilbao',
		'Burgos',
		'Ciudad Real',
		'Fuerteventura',
		'Girona Costa Brava',
		'Gibraltar',
		'Gran Canaria',
		'Granada',
		'Huesca Pirineos',
		'Ibiza',
		'Santa Cruz de la Palma',
		'Lanzarote',
		'Lleida',
		'Leon',
		'Lugo',
		'Madrid',
		'Minorca',
		'Murcia San Javier',
		'Palma de Mallorca',
		'Pamplona',
		'Reus',
		'Santander',
		'Salamanca',
		'Seville',
		'Tenerife',
		'Valencia',
		'Valladolid',
		'Zaragoza',
		'Zamora',
		#Sweden
		'Arvidsjaur',
		'Boden',
		'Gotland',
		'Gothenburg',
		'Haparanda',
		'Kiruna',
		'Karlstad',
		'Nikkaluokta',
		'Stockholm',
		'Uppsala',
		'Visby',
		#Switzerland
		'Basel',
		'Bern',
		'Bellinzona',
		'Biel',
		'Geneva',
		'Lucerne',
		'Lousanne',
		'Lugano',
		'Neuchatel',
		'St Gallen',
		'Thun',
		'Winterthur',
		'Yverdon-les-Bains',
		'Zurich',
		'Zug',
		#Turkey
		'Adana',
		'Ankara',
		'Antalya',
		'Aydin',
		'Batman',
		'Bafra',
		'Bolu',
		'Bodrum',
		'Bursa',
		'Dalaman',
		'Denizli',
		'Diyarbakir',
		'Erzurum',
		'Gaziantep',
		'Istanbul',
		'Isparta',
		'Igdir',
		'Izmir',
		'Kayseri',
		'Konya',
		'Kahramanmaras',
		'Malatya',
		'Mersin',
		'Mardin',
		'Nevsehir',
		'Ordu',
		'Rize',
		'Samsun',
		'Sivas',
		'Siirt',
		'Tokat',
		'Trabzon',
		'Zonguldak',
		#Ukraine
		'Kiev',
		'Chernivtsi',
		'Donetsk',
		'Dnipropetrovsk',
		'Kharkiv',
		'Kerson',
		'Kryvyi Rih',
		'Kyiv Zhuliany',
		'Kirovohrad',
		'Lviv',
		'Luhansk',
		'Mariupol',
		'Odessa',
		'Poltava',
		'Mykolaiv',
		'Simferopol',
		'Sumy',
		'Vinnytsia',
		'Zaporizhia',
		'Zhytomyr',
		#United Kingdom
		'Aberdeen',
		'Belfast',
		'Birmingham',
		'Blackpool',
		'Bournemouth',
		'Bristol',
		'Brighton',
		'Cardiff',
		'Chester',
		'Canterbury',
		'Derry',
		'Dundee',
		'Durham',
		'Edinburgh',
		'East Midlands',
		'Exeter',
		'Glasgow',
		'Hull',
		'Inverness',
		'Ipswich',
		'Kirkwall',
		'Leeds',
		'Liverpool',
		'Leicester',
		'London',
		'Manchester',
		'Newcastle',
		'Nottingham',
		'Cornwall',
		'Norwich',
		'Oxford',
		'Paisley',
		'Perth',
		'Peterborough',
		'Sheffield',
		'Southampton',
		'Stornoway',
		'Swindon',
		'Swansea',
		'Torquay',
		'York',
	],
	'Oceania':[
		#Australia
		'Adelaide',
		'Alice Springs',
		'Brisbane',
		'Border Village',
		'Byron Bay',
		'Cairns',
		'Canberra',
		'Coober Pedy',
		'Cocklebiddy',
		'Coral Bay',
		'Darwin',
		'Esperance',
		'Fitzroy Crossing',
		'Gold Coast',
		'Hobart',
		'Kangaroo Island',
		'Longreach',
		'Mackay',
		'Melbourne',
		'Mullumbimby',
		'Newman',
		'Perth',
		'Port Augusta',
		'Port Hedland',
		'Sydney',
		#New Zealand
		'Auckland',
		'Christchurch',
		'Dunedin',
		'Gisborne',
		'Hamilton',
		'Invercargill',
		'Nelson',
		'Queenstown',
		'Rotorua',
		'Timaru',
		'Wanaka',
		'Wellington',
		#Islands
		'Adamstwon',
		'Roto',
		'Ahurei',
		'Areora',
		'Atuona',
		'Arutanga',
		'Akamaru',
		'Baie Ste Anne',
		'Christmas Island',
		'Cocos Islands',
		'Daniel',
		'Ducie Island',
		'Desroches Island',
		'Fare',
		'Foumbouni',
		'Keeling',
		'Rarotonga',
		'Nadi',
		'Suva',
		'Pape\'ete',
		'Glorioso Islands',
		'Henderson Island',
		'Heard Island',
		'Kiritimati',
		'Tarawa',
		'Kwajalein',
		'Launceston',
		'Lauren',
		'La Roche Godon',
		'La Digue Island',
		'Bird Island',
		'McDonald Islands',
		'Mutuaura',
		'Majuro',
		'Maldives',
		'Chuuk',
		'Kosrae',
		'Pohnpei',
		'Yap',
		'Yaren',
		'White Sands',
		'Noumea',
		'Norfolk',
		'Yos Sudarso',
		'Saipan Island',
		'San Christobal',
		'Raivavae',
		'Rikitea',
		'Rota Island',
		'Taravai',
		'Tinian Island',
		'Thinadhoo',
		'Thursday Island',
		'Totegegie',
		'Alofi',
		'Korror',
		'Port Moresby',
		'Port Mathurin',
		'Apia',
		'Honiara',
		'Nuku\'alofa',
		'Funafuti',
		'Port Vila',
		'Futuna',
		'Wallis',
	],
	'ANTARCTICA': [
		'Davis Station',
		'Casey Station',
		'Concordia Station',
		'McMurdo',
	]
}
